version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '80:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=cbas@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres

  server:
    build: .
    restart: always

    ports:
      - '8000:8000'
    volumes:
      - .:/backend
    depends_on:
      - postgres
volumes:
  pgdata:
