# Generated by Django 5.0.1 on 2024-02-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='modules',
            field=models.ManyToManyField(to='school.module'),
        ),
    ]
